base_model = "alibaba/qwen3-coder-480b-a35b-instruct"
release_date = "2026-04-30"
last_updated = "2026-07-21"

[cost]
input = 0.601
output = 2.085
cache_write = 0.3005

[limit]
context = 106_000
output = 10_600
