base_model = "openai/o3-deep-research"
temperature = true

[[reasoning_options]]
type = "effort"
values = ["medium"]

[cost]
input = 10
output = 40
cache_read = 2.5

[limit]
input = 100_000

[modalities]
input = ["text", "image", "pdf"]
