base_model = "alibaba/qwen3.7-plus"
reasoning_options = [{ type = "toggle" }]

[cost]
input = 0.14
output = 0.55
cache_read = 0.01
cache_write = 0.17

[[cost.tiers]]
tier = { size = 256_000 }
input = 0.14
output = 0.55
cache_read = 0.01
cache_write = 0.17
