base_model = "google/gemini-2.5-flash"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "budget_tokens"
min = 0
max = 24_576

[cost]
input = 0.15
output = 1.25
cache_read = 0.015
input_audio = 1.00
